<?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
<div class="form-list debit-payment" id="payment_form_<?php /* @noEscape */ echo $methodCode ?>" style="display:none;">
    <div class="<?php /* @noEscape */ echo $methodCode ?>-instructions-content checkout-agreement-item-content">
        <form class="debit_form" id="debit_form" action="#" method="post" >
            <div class="admin__field field-iban">
                <label class="label admin__field-label" for="order-billing_iban"><span>IBAN</span></label>
                <div class="admin__field-control value">
                    <input id="order-billing_iban" name="payment[iban]" value="" class="input-text admin__control-text" type="text">
                </div>
            </div>
        </form>
    </div>
</div>

